const fs = require('node:fs');
const path = require('node:path');
const file = path.resolve(__dirname, '../../file/n2_vocabulary.json');
const data = JSON.parse(fs.readFileSync(file, 'utf8'));
const words = data.units.flatMap((u) => u.parts.flatMap((p) => p.words));
const seg = (j, t, r = t) => { const i = j.indexOf(t); return i < 0 ? [{ text: j, reading: '', isUnderlined: false }] : [{ text: j.slice(0, i), reading: '', isUnderlined: false }, { text: t, reading: r, isUnderlined: true }, { text: j.slice(i + t.length), reading: '', isUnderlined: false }].filter((x) => x.text); };
const ex = (j, v, t, r, p) => ({ japanese: j, vietnamese: v, segments: seg(j, t, r), source: { pdfPage: p, printedPage: p - 3 } });
const set = (n, patch) => Object.assign(words.find((w) => w.sourceNumber === n), patch);

set(605, { hanVietMeaning: 'PHÂN ĐAM', meaning: 'Phân chia', relations: [{ label: '合', items: [{ japanese: '＿役割', vietnamese: 'Chia sẻ trách nhiệm', segments: seg('＿役割', '＿', ''), source: { pdfPage: 167, printedPage: 164 } }] }] });
set(606, { meaning: 'Đảm đương', examples: [ex('会社で営業を担当している。', 'Tôi đang phụ trách mảng kinh doanh trong công ty.', '担当', 'たんとう', 167), ex('担当の医師から検査結果の説明を受けた。', 'Tôi được bác sĩ phụ trách giải thích kết quả xét nghiệm.', '担当', 'たんとう', 167)] });
set(607, { hanVietMeaning: 'GIAO THẾ／GIÁO ĐẠI', meaning: 'Thay đổi', examples: [ex('首相が交代した。', 'Thủ tướng đã thay đổi.', '交代', 'こうたい', 167), ex('サッカーではA選手がB選手に交代した。', 'Trong bóng đá, cầu thủ A đã được thay bằng cầu thủ B.', '交代', 'こうたい', 167)], relations: [{ label: '合', items: [{ japanese: '世代交代', vietnamese: 'Chuyển giao thế hệ (Sự thay thế của các thế hệ)', segments: seg('世代交代', '交代', 'こうたい'), source: { pdfPage: 167, printedPage: 164 } }] }] });
set(608, { meaning: 'Đại diện' });
set(611, { kanji: '予測', hiragana: 'よそく', hanVietMeaning: 'DỰ TRẮC', meaning: 'Dự đoán, ước tính', examples: [ex('データに基づいて結果を予測する。', 'Dự đoán kết quả dựa vào dữ liệu.', '予測', 'よそく', 168), ex('売り上げ予測がはずれた。', 'Dự đoán doanh thu bị lệch.', '予測', 'よそく', 168), ex('客がどれぐらい来るか、予測がつかない。', 'Tôi không dự đoán được có bao nhiêu khách hàng sẽ đến.', '予測', 'よそく', 168)], relations: [{ label: '連', items: [{ japanese: '＿がつく⇔つかない', vietnamese: 'Dự đoán được ⇔ Không dự đoán được', segments: seg('＿がつく⇔つかない', '＿', ''), source: { pdfPage: 168, printedPage: 165 } }, { japanese: '＿があたる⇔はずれる', vietnamese: 'Đúng như dự đoán ⇔ Ngoài dự đoán', segments: seg('＿があたる⇔はずれる', '＿', ''), source: { pdfPage: 168, printedPage: 165 } }] }, { label: '類', items: [{ japanese: '予想', vietnamese: 'Dự đoán', segments: seg('予想', '予想', 'よそう'), source: { pdfPage: 168, printedPage: 165 } }] }, { label: '関', items: [{ japanese: '予測', vietnamese: 'Dự đoán trước／sự mong đợi', segments: seg('予測', '予測', 'よそく'), source: { pdfPage: 168, printedPage: 165 } }] }] });
set(612, { kanji: '予想', hiragana: 'よそう', hanVietMeaning: 'DỰ TƯỞNG', meaning: 'Sự mong đợi', examples: [ex('今回の実験では、予想に反し、いいデータが得られなかった。', 'Trái với mong đợi, trong kỳ thực tập này tôi đã không thể lấy được dữ liệu tốt.', '予想', 'よそう', 168), ex('予想外のことが起こって、仕事のスケジュールが大幅に遅れてしまった。', 'Những điều bất ngờ (trái với sự mong đợi) xảy ra nên lịch trình làm việc bị chậm trễ rất nhiều.', '予想', 'よそう', 168)], relations: [{ label: '連', items: [{ japanese: '＿に反する', vietnamese: 'Trái với sự mong đợi', segments: seg('＿に反する', '＿', ''), source: { pdfPage: 168, printedPage: 165 } }] }, { label: '類', items: [{ japanese: '予想（する）', vietnamese: 'Dự đoán, sự báo trước', segments: seg('予想（する）', '予想（する）', 'よそう（する）'), source: { pdfPage: 168, printedPage: 165 } }] }] });
set(613, { kanji: '判断', hiragana: 'はんだん', hanVietMeaning: 'PHÁN ĐOÁN', meaning: 'Phán đoán', examples: [ex('外見や肩書きで人を判断するのはよくない。', 'Việc phán đoán một người bằng bề ngoài và chức vụ là không tốt.', '判断', 'はんだん', 168), ex('どちらが正しいか、判断がつかない。', 'Tôi không đoán được đâu là đúng.', '判断', 'はんだん', 168), ex('年を取ると判断力が衰えてくるものだ。', 'Khi có tuổi, năng lực phán đoán sẽ bị suy giảm.', '判断', 'はんだん', 168)], relations: [{ label: '連', items: [{ japanese: '＿がつく⇔つかない', vietnamese: 'Phán đoán được ⇔ Không thể phán đoán được', segments: seg('＿がつく⇔つかない', '＿', ''), source: { pdfPage: 168, printedPage: 165 } }, { japanese: '＿を下す', vietnamese: 'Đưa ra phán đoán', segments: seg('＿を下す', '＿', ''), source: { pdfPage: 168, printedPage: 165 } }] }, { label: '合', items: [{ japanese: '＿力', vietnamese: 'Năng lực phán đoán', segments: seg('＿力', '＿', ''), source: { pdfPage: 168, printedPage: 165 } }, { japanese: '＿材料', vietnamese: 'Cơ sở đánh giá', segments: seg('＿材料', '＿', ''), source: { pdfPage: 168, printedPage: 165 } }, { japanese: '自＿', vietnamese: 'Tự đánh giá', segments: seg('自＿', '＿', ''), source: { pdfPage: 168, printedPage: 165 } }] }, { label: '関', items: [{ japanese: '考える', vietnamese: 'Suy nghĩ', segments: seg('考える', '考える', 'かんがえる'), source: { pdfPage: 168, printedPage: 165 } }] }] });
set(614, { kanji: '評価', hiragana: 'ひょうか', hanVietMeaning: 'BÌNH GIÁ', meaning: 'Đánh giá, định giá', examples: [ex('この映画に対する世間の評価は高い。', 'Sự đánh giá của công chúng đối với bộ phim này cao.', '評価', 'ひょうか', 168), ex('成績を五段階で評価する。', 'Đánh giá thành tích dựa trên 5 cấp độ.', '評価', 'ひょうか', 168), ex('地球温暖化についてのレポートは彼の評価を高めた。', 'Bản báo cáo đã đánh giá cao nhận định của anh ấy về sự nóng lên của trái đất.', '評価', 'ひょうか', 168)], relations: [] });

const { computeCandidateHash } = require('../vocabulary/validateN2Vocabulary');
data.verification = { ...(data.verification || {}), approved: true, method: 'manual-page-by-page', issues: ['Manual audit continued through PDF page 168; remaining pages require review.'] };
data.verification.candidateHash = computeCandidateHash(data);
fs.writeFileSync(file, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
console.log('Updated N2 words 605-614 from PDF pages 167-168.');
