const fs=require('node:fs');const path=require('node:path');const file=path.resolve(__dirname,'../../file/n2_vocabulary.json');const d=JSON.parse(fs.readFileSync(file,'utf8'));const ws=d.units.flatMap(u=>u.parts.flatMap(p=>p.words));const seg=(j,t,r=t)=>{const i=j.indexOf(t);return i<0?[{text:j,reading:'',isUnderlined:false}]:[{text:j.slice(0,i),reading:'',isUnderlined:false},{text:t,reading:r,isUnderlined:true},{text:j.slice(i+t.length),reading:'',isUnderlined:false}].filter(x=>x.text)};const ex=(j,v,t,r,p)=>({japanese:j,vietnamese:v,segments:seg(j,t,r),source:{pdfPage:p,printedPage:p-3}});const set=(n,p)=>Object.assign(ws.find(w=>w.sourceNumber===n),p);
set(658,{kanji:'増税',hiragana:'ぞうぜい',hanVietMeaning:'TĂNG THUẾ',meaning:'Tăng thuế',examples:[ex('労働人口が減少し、政府は増税を考えているらしい。','Do dân số lao động giảm nên hình như chính phủ đang cân nhắc việc tăng thuế.','増税','ぞうぜい',182),ex('所得税が増税された。','Thuế thu nhập đã bị tăng lên.','増税','ぞうぜい',182)]});
set(659,{kanji:'増員',hiragana:'ぞういん',hanVietMeaning:'TĂNG VIÊN',meaning:'Tăng nhân lực',examples:[ex('アメリカ大統領が来日するに当たり、警備員が増員された。','Khi tổng thống Mỹ viếng thăm Nhật Bản, số lượng nhân viên an ninh đã được tăng thêm.','増員','ぞういん',182),ex('定員を増員する。','Tăng số ghế (số người quy định).','増員','ぞういん',182)]});
set(660,{kanji:'減点',hiragana:'げんてん',hanVietMeaning:'GIẢM ĐIỂM',meaning:'Giảm điểm',examples:[ex('漢字のテストで、送り仮名を間違えて減点された。','Trong bài kiểm tra kanji, tôi bị nhầm phiên âm chữ Hán nên đã bị trừ điểm.','減点','げんてん',182)]});
set(661,{kanji:'減退',hiragana:'げんたい',hanVietMeaning:'GIẢM THOÁI',meaning:'Suy thoái, suy giảm',examples:[ex('暑さのせいで食欲が減退した。','Do thời tiết nóng bức khiến cảm giác muốn ăn giảm đi.','減退','げんたい',183)],relations:[{label:'対',items:[{japanese:'増進',vietnamese:'Tăng thêm',segments:seg('増進','増進','ぞうしん'),source:{pdfPage:183,printedPage:180}}]}]});
set(662,{kanji:'減量',hiragana:'げんりょう',hanVietMeaning:'GIẢM LƯỢNG',meaning:'Giảm (trọng lượng, số lượng)',examples:[ex('洗剤の中身が減量された。これは値上げと同じだ。','Khối lượng bột giặt bị giảm. Điều này cũng giống như việc tăng giá vậy.','減量','げんりょう',183),ex('ボクサーの加藤選手は試合前の減量に苦しんでいる。','Võ sĩ quyền anh Kato đang vất vả vì giảm cân trước trận đấu.','減量','げんりょう',183)]});
set(663,{kanji:'開発',hiragana:'かいはつ',hanVietMeaning:'KHAI PHÁT',meaning:'Phát triển',examples:[ex('資源を開発する。','Khai thác tài nguyên.','開発','かいはつ',183),ex('海辺を開発してリゾート地にする。','Khai thác khu vực bãi biển làm khu nghỉ dưỡng.','開発','かいはつ',183),ex('駅前の再開発が行われている。','Nhà ga đang được tiến hành xây dựng lại.','開発','かいはつ',183),ex('新薬の開発に成功した。','Thành công trong việc phát triển loại thuốc mới.','開発','かいはつ',183),ex('新商品を開発する。','Phát triển sản phẩm mới.','開発','かいはつ',183)]});
set(664,{kanji:'開店',hiragana:'かいてん',hanVietMeaning:'KHAI ĐIẾM',meaning:'Mở cửa hàng, khai trương',examples:[ex('近所に新しいレストランが開店した。','Có một nhà hàng mới mở ở gần đây.','開店','かいてん',183),ex('開店祝いに花束を贈った。','Tôi đã gửi tặng bó hoa nhân dịp chúc mừng khai trương cửa hàng.','開店','かいてん',183),ex('「開店は10時です」','“Thời gian mở cửa là 10 giờ.”','開店','かいてん',183)]});
const {computeCandidateHash}=require('../vocabulary/validateN2Vocabulary');d.verification.candidateHash=computeCandidateHash(d);fs.writeFileSync(file,`${JSON.stringify(d,null,2)}\n`,'utf8');console.log('Updated N2 words 658-664 from PDF pages 182-183.');
